### ISSUE TITLE
README.md with Travis-CI badge

### ISSUE THREAD

**Issue by szabgab** [perlpunk/YAML-LibYAML-API-p5#5]
Hi Tina,

I think it is fairly common to have a README.md in the repository of the project, with a Travis-CI badge and link to the results.
Would you like me to send PR for that?

**Comment by perlpunk** [comment]
Thanks!
I actually added one myself now.
I am using Github Actions now, and Travis CI just as a backup.
The commits have a little icon showing the test results; I think I don't need a badge.

**Comment by szabgab** [comment]
:+1:
