### ISSUE TITLE
libyaml license violation

### ISSUE THREAD

**Issue by ppisar** [perlpunk/YAML-LibYAML-API-p5#6]
Your repository, as well as a tar ball on CPAN, distributes significant pieces of libyaml-0.2.5 project. E.g. LibYAML/api.c file. The libyaml code is covered by MIT license <https://raw.githubusercontent.com/yaml/libyaml/master/License> which reads:

> Permission is hereby granted [...] to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software [...], subject to the following conditions:
>
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

But I cannot find the libyaml's copyright notice and permission notice anywhere in your repository.

To comply with the license terms, please add the libyaml's License file into LibYAML directory of you repository.

**Comment by perlpunk** [comment]
Thanks!
I guess I have to add the `license` in `dist.ini` too. Will have to find out how to add multiple licenses there.

And https://metacpan.org/release/YAML-LibYAML has the same issue.

**Comment by perlpunk** [comment]
I just changed the whole license to MIT because I don't know how to add multiple licenses to a module.
Just released version 0.012_001

**Comment by ppisar** [comment]
Great. Thanks.

**Comment by perlpunk** [comment]
This was released with 0.013, I just forgot to close
